In [ ]:
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# **Customer Churn - Use Case Implementation**

# **Disclaimer**

All software and hardware used or referenced in this guide belong to their respective vendor. We developed this guide based on our development infrastructure and this guide may or may not work on others systems and technical infrastructure. We are not liable for any direct or indirect problems caused by users using this guide.

# **Executive Summary**

The purpose of this document is to provide adequate information to users to implement Logistic Regression or XGBoost (supervised machine learning) model in Google Colab. In order to achieve this, we are using one of the most common problem which is Customer Churn that occurs at most of the industries.

# **Problem Statement**

Our Client experiences high customer churn rate which indicates that the company is losing customers at an alarming rate and it can be due to various reasons. Our objective is to predict the customers accurately who are more likely to churn using Machine Learning Algorithm. This will help the company to know in advance, the customers who are more likely to leave company's service and compe up with retention strategies/policies.

# **Challenges**

To succeed in today’s complex business scenario, companies need to build and deploy an effective customer churn analysis model in order to monitor churn rate and maximize customer retention. Acquiring new customers always costs heavily and this makes the predictive churn model appealing for businesses that aim at retaining customers and maximizing profits.

# **STEP 0: INI FILE CONFIGURATION**

In [ ]:
import os

vAR_Config = configparser.ConfigParser(allow_no_value=True)

vAR_INI_FILE_PATH = os.getenv('CUS_CHURN_FT_XG')

vAR_INI_FILE_PATH

vAR_Config.read(vAR_INI_FILE_PATH)

vAR_Data = vAR_Config.sections()

vAR_Config.sections()

vAR_Train_Data = vAR_Config['FILE PATH']['TRAINING_DATA']

vAR_Training_Data_Excel_Worsheet = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET']
print(vAR_Training_Data_Excel_Worsheet)

vAR_Train_Data_CUS = vAR_Config['FILE PATH']['TRAINING_DATA(CUS)']

vAR_Training_Data_Excel_Worsheet_CUS  = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET(CUS)']
print(vAR_Training_Data_Excel_Worsheet_CUS)

vAR_Training_Data_CBP = vAR_Config['FILE PATH']['TRAINING_DATA(CBP)']

vAR_Training_Data_Excel_Worsheet_CBP = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET(CBP)']
print(vAR_Training_Data_Excel_Worsheet_CBP)

vAR_Training_Data_CPP = vAR_Config['FILE PATH']['TRAINING_DATA(CPP)']

vAR_Training_Data_Excel_Worsheet_CPP = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET(CPP)']
print(vAR_Training_Data_Excel_Worsheet_CPP)

vAR_Training_Data_CSP = vAR_Config['FILE PATH']['TRAINING_DATA(CSP)']

vAR_Training_Data_Excel_Worsheet_CSP = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET(CSP)']
print(vAR_Training_Data_Excel_Worsheet_CSP)

vAR_Training_Data_CSQ = vAR_Config['FILE PATH']['TRAINING_DATA(CSQ)']

vAR_Training_Data_Excel_Worsheet_CSQ = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET(CSQ)']
print(vAR_Training_Data_Excel_Worsheet_CSQ)

vAR_Training_Data_CS = vAR_Config['FILE PATH']['TRAINING_DATA(CS)']

vAR_Training_Data_Excel_Worsheet_CS = vAR_Config['FILE PATH']['TRAINING_DATA_EXCEL_WORKSHEET(CS)']
print(vAR_Training_Data_Excel_Worsheet_CS)

vAR_Test_Data = vAR_Config['FILE PATH']['TEST_DATA']
print(vAR_Test_Data)

vAR_Test_Data_Excel_Worsheet = vAR_Config['FILE PATH']['TEST_DATA_EXCEL_WORKSHEET']
print(vAR_Test_Data_Excel_Worsheet)

vAR_Model_Outcome_LG = vAR_Config['FILE PATH']['MODEL_OUTCOME_LG']
print(vAR_Model_Outcome_LG)
vAR_Model_Outcome_XG = vAR_Config['FILE PATH']['MODEL_OUTCOME_XG']
print(vAR_Model_Outcome_XG)

# **STEP 1: IMPORT THE LIBRARIES**

In [1]:
import pandas as vAR_pd

import xgboost as vAR_xgb 

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier

!pip install featuretools
import featuretools as ft

Collecting featuretools
  Downloading https://files.pythonhosted.org/packages/e2/13/d28a29bb0438d69496a97a4c6818ee3c0b3a0f9ade169bd252c05370e495/featuretools-0.23.2-py3-none-any.whl (296kB)
     |████████████████████████████████| 296kB 14.8MB/s
Requirement already satisfied: psutil>=5.4.8 in /usr/local/lib/python3.7/dist-packages (from featuretools) (5.4.8)
Requirement already satisfied: click>=7.0.0 in /usr/local/lib/python3.7/dist-packages (from featuretools) (7.1.2)
Requirement already satisfied: pyyaml>=3.12 in /usr/local/lib/python3.7/dist-packages (from featuretools) (3.13)
Requirement already satisfied: cloudpickle>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from featuretools) (1.3.0)
Collecting distributed>=2.12.0
  Downloading https://files.pythonhosted.org/packages/96/b7/f58dd1e30f940a8b38de10f5d92b2fce08f38dcba3eb1ddb017260588ed4/distributed-2021.3.0-py3-none-any.whl (675kB)
     |████████████████████████████████| 675kB 26.4MB/s
Requirement already satisfied: pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1 in /usr/local/lib/python3.7/dist-packages (from featuretools) (1.1.5)
Requirement already satisfied: dask[dataframe]>=2.12.0 in /usr/local/lib/python3.7/dist-packages (from featuretools) (2.12.0)
Requirement already satisfied: tqdm>=4.32.0 in /usr/local/lib/python3.7/dist-packages (from featuretools) (4.41.1)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.7/dist-packages (from featuretools) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from featuretools) (1.19.5)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (2.3.0)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (2.0.0)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (0.11.1)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (1.7.0)
Requirement already satisfied: tornado>=5; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (5.1.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (54.0.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2.12.0->featuretools) (1.0.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1->featuretools) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1->featuretools) (2.8.1)
Collecting partd>=0.3.10; extra == "dataframe"
  Downloading https://files.pythonhosted.org/packages/44/e1/68dbe731c9c067655bff1eca5b7d40c20ca4b23fd5ec9f3d17e201a6f36b/partd-1.1.0-py3-none-any.whl
Collecting fsspec>=0.6.0; extra == "dataframe"
  Downloading https://files.pythonhosted.org/packages/91/0d/a6bfee0ddf47b254286b9bd574e6f50978c69897647ae15b14230711806e/fsspec-0.8.7-py3-none-any.whl (103kB)
     |████████████████████████████████| 112kB 49.8MB/s
Requirement already satisfied: heapdict in /usr/local/lib/python3.7/dist-packages (from zict>=0.1.3->distributed>=2.12.0->featuretools) (1.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas!=1.1.0,!=1.1.1,<2.0.0,>=0.24.1->featuretools) (1.15.0)
Collecting locket
  Downloading https://files.pythonhosted.org/packages/50/b8/e789e45b9b9c2db75e9d9e6ceb022c8d1d7e49b2c085ce8c05600f90a96b/locket-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from fsspec>=0.6.0; extra == "dataframe"->dask[dataframe]>=2.12.0->featuretools) (3.7.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->fsspec>=0.6.0; extra == "dataframe"->dask[dataframe]>=2.12.0->featuretools) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->fsspec>=0.6.0; extra == "dataframe"->dask[dataframe]>=2.12.0->featuretools) (3.7.4.3)
ERROR: distributed 2021.3.0 has requirement cloudpickle>=1.5.0, but you'll have cloudpickle 1.3.0 which is incompatible.
ERROR: distributed 2021.3.0 has requirement dask>=2021.03.0, but you'll have dask 2.12.0 which is incompatible.
Installing collected packages: distributed, featuretools, locket, partd, fsspec
  Found existing installation: distributed 1.25.3
    Uninstalling distributed-1.25.3:
      Successfully uninstalled distributed-1.25.3
Successfully installed distributed-2021.3.0 featuretools-0.23.2 fsspec-0.8.7 locket-0.2.1 partd-1.1.0

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **STEP 2: IMPORT THE TRAINING DATA**

In [5]:
import warnings
warnings.filterwarnings('ignore')
Customer_Label = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/Customer_label.xlsx")
Customer = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/Customer.xlsx")
Customer_Buying_Pattern = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/customer_buying_pattern.xlsx")
Customer_Product_Price = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/Customer_Product_Price.xlsx")
Customer_Spending_Power = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/Customer_Spending_Power.xlsx")
Customer_Service_Quality = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/Customer_Service_Quality.xlsx")
Customer_Satisfaction = vAR_pd.read_excel("/content/drive/MyDrive/Customer_Churn_Datasets/Customer_Satisfaction.xlsx")

In [6]:
#Checking for null values
print(Customer_Label.isnull().sum())
print(Customer.isnull().sum())
print(Customer_Buying_Pattern.isnull().sum())
print(Customer_Product_Price.isnull().sum())
print(Customer_Spending_Power.isnull().sum())
print(Customer_Service_Quality.isnull().sum())
print(Customer_Satisfaction.isnull().sum())

CustomerID          0
Customer Code       0
CustomerRegion      0
CustomerLocation    0
CustomerChurn       1
dtype: int64
CustomerID          0
Customer Code       0
CustomerRegion      0
CustomerLocation    0
dtype: int64
CustomerID                       0
Product                          0
Quantity(in lots)                0
CBPID                            0
customer lifetime in years       0
Average yearly purchase          0
average Monthly wise purchase    0
Last year purchase               0
dtype: int64
CustomerID                     0
Product                        0
CPPID                          0
Price Amount                   0
product average unit price     0
last year unit price           0
dtype: int64
CustomerID                              0
Product                                 0
CSPID                                   0
 Amount spent in lifetime(in millon)    0
Average amount spend per year           0
last year amount spend                  0
dtype: int64
CustomerID                 0
Product                    0
CSQID                      0
Service Call               0
Service Failure Rate%pa    0
last year failure rate%    0
dtype: int64
CustomerID              0
Product                 0
CSID                    0
Service Call            0
Average call in year    0
last year calls         0
dtype: int64

In [7]:
#Replacing missing value with Mode value 
Customer_Label['CustomerChurn'].fillna(Customer_Label['CustomerChurn'].mode()[0], inplace=True)
print(Customer_Label.isnull().sum())

CustomerID          0
Customer Code       0
CustomerRegion      0
CustomerLocation    0
CustomerChurn       0
dtype: int64

# **STEP 3(b): FEATURE SELECTION(USING FEATURE TOOLS)**

In [8]:
#DEFINING THE ENTITIES
es = ft.EntitySet(id="CUSTOMER_CHURN")
es1 = es.entity_from_dataframe(entity_id = 'Customer', dataframe = Customer, index='CustomerID')
es2 = es.entity_from_dataframe(entity_id = 'CustomerBuyingPattern', dataframe = Customer_Buying_Pattern, index='CBPID')
es3 = es.entity_from_dataframe(entity_id = 'CustomerProductPurchase', dataframe = Customer_Product_Price, index='CPPID')
es4 = es.entity_from_dataframe(entity_id = 'CustomerSpendingPower', dataframe = Customer_Spending_Power, index = 'CSPID')
es5 = es.entity_from_dataframe(entity_id = 'CustomerServiceQuality', dataframe = Customer_Service_Quality, index = 'CSQID')
es6 = es.entity_from_dataframe(entity_id = 'CustomerSatisfaction', dataframe = Customer_Satisfaction, index = 'CSID')
es

Entityset: CUSTOMER_CHURN
  Entities:
    Customer [Rows: 2104, Columns: 4]
    CustomerBuyingPattern [Rows: 2104, Columns: 8]
    CustomerProductPurchase [Rows: 2104, Columns: 6]
    CustomerSpendingPower [Rows: 2104, Columns: 6]
    CustomerServiceQuality [Rows: 2104, Columns: 6]
    CustomerSatisfaction [Rows: 2104, Columns: 6]
  Relationships:
    No relationships

In [9]:
#DEFINING THE RELATIONSHIP
es.add_relationship(ft.Relationship(es['Customer']['CustomerID'],es['CustomerBuyingPattern']['CustomerID']))
es.add_relationship(ft.Relationship(es['Customer']['CustomerID'],es['CustomerProductPurchase']['CustomerID']))
es.add_relationship(ft.Relationship(es['Customer']['CustomerID'],es['CustomerSpendingPower']['CustomerID']))
es.add_relationship(ft.Relationship(es['Customer']['CustomerID'],es['CustomerServiceQuality']['CustomerID']))
es.add_relationship(ft.Relationship(es['Customer']['CustomerID'],es['CustomerSatisfaction']['CustomerID']))

Entityset: CUSTOMER_CHURN
  Entities:
    Customer [Rows: 2104, Columns: 4]
    CustomerBuyingPattern [Rows: 2104, Columns: 8]
    CustomerProductPurchase [Rows: 2104, Columns: 6]
    CustomerSpendingPower [Rows: 2104, Columns: 6]
    CustomerServiceQuality [Rows: 2104, Columns: 6]
    CustomerSatisfaction [Rows: 2104, Columns: 6]
  Relationships:
    CustomerBuyingPattern.CustomerID -> Customer.CustomerID
    CustomerProductPurchase.CustomerID -> Customer.CustomerID
    CustomerSpendingPower.CustomerID -> Customer.CustomerID
    CustomerServiceQuality.CustomerID -> Customer.CustomerID
    CustomerSatisfaction.CustomerID -> Customer.CustomerID

In [10]:
feature_matrix_Customer, feature_defs = ft.dfs(entityset=es, target_entity="Customer")
feature_matrix_Customer

           Customer Code  ... SUM(CustomerSatisfaction.last year calls)
CustomerID                ...
18001              CUST1  ...                                       0.0
18002              CUST2  ...                                      58.0
18003              CUST3  ...                                      67.0
18004              CUST4  ...                                     106.0
18005              CUST5  ...                                       2.0
...                  ...  ...                                       ...
20100           CUST2100  ...                                       0.0
20101           CUST2101  ...                                     103.0
20102           CUST2102  ...                                      42.0
20103           CUST2103  ...                                     132.0
20104           CUST2104  ...                                       0.0

[2104 rows x 116 columns]

In [11]:
feature_matrix_Customer, feature_defs = ft.dfs(entityset=es, target_entity="Customer", agg_primitives=["SUM"], max_depth=2) 
feature_matrix_Customer

           Customer Code  ... SUM(CustomerSatisfaction.last year calls)
CustomerID                ...
18001              CUST1  ...                                       0.0
18002              CUST2  ...                                      58.0
18003              CUST3  ...                                      67.0
18004              CUST4  ...                                     106.0
18005              CUST5  ...                                       2.0
...                  ...  ...                                       ...
20100           CUST2100  ...                                       0.0
20101           CUST2101  ...                                     103.0
20102           CUST2102  ...                                      42.0
20103           CUST2103  ...                                     132.0
20104           CUST2104  ...                                       0.0

[2104 rows x 19 columns]

In [12]:
vAR_Featuresft = feature_matrix_Customer.iloc[:,3:]
vAR_Featuresft.head()

            SUM(CustomerBuyingPattern.Average yearly purchase)  ...  SUM(CustomerSatisfaction.last year calls)
CustomerID                                                      ...
18001                                                   370.0   ...                                        0.0
18002                                                   353.0   ...                                       58.0
18003                                                   892.0   ...                                       67.0
18004                                                     0.0   ...                                      106.0
18005                                                     0.0   ...                                        2.0

[5 rows x 16 columns]

# **DEFINING THE LABELS**

In [13]:
vAR_label = Customer_Label.iloc[:,4:]
vAR_label

      CustomerChurn
0               1.0
1               1.0
2               0.0
3               0.0
4               1.0
...             ...
2099            0.0
2100            1.0
2101            0.0
2102            1.0
2103            0.0

[2104 rows x 1 columns]

In [14]:
vAR_Featuresft=vAR_Featuresft.dropna()

In [15]:
vAR_Featuresft=vAR_Featuresft.astype(int)

# **STEP 4: IMPORT THE MODEL**

In [16]:
vAR_X_TRAIN, vAR_X_TEST, vAR_Y_TRAIN, vAR_Y_TEST = train_test_split(vAR_Featuresft, vAR_label, test_size=0.20, random_state=0)

#Logistic Regression
vAR_Model1 = LogisticRegression()

#XGBoost
vAR_Model2 = XGBClassifier(eta=0.01,gamma=10)

In [ ]:
#Fitting the logistic regression model
vAR_Model1.fit(vAR_X_TRAIN,vAR_Y_TRAIN)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#Fitting the XGBoost model
vAR_Model2.fit(vAR_X_TRAIN,vAR_Y_TRAIN)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=0.01, gamma=10,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
#Prediction using Logistic regression
vAR_Labels_predLG = vAR_Model1.predict(vAR_X_TEST)

In [ ]:
#Prediction using XGBoost
vAR_Labels_predXG = vAR_Model2.predict(vAR_X_TEST)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(vAR_Y_TEST, vAR_Labels_predLG)

array([[224,  26],
       [154,  17]])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(vAR_Y_TEST, vAR_Labels_predXG)

array([[250,   0],
       [171,   0]])

In [ ]:
#Checking accuracy for XGBoost
from sklearn.metrics import accuracy_score
accuracy_score(vAR_Y_TEST, vAR_Labels_predXG)

0.5938242280285035

In [ ]:
#Checking accuracy for Logistic Regression
from sklearn.metrics import accuracy_score
accuracy_score(vAR_Y_TEST, vAR_Labels_predLG)

0.5724465558194775

In [ ]:
#from sklearn.model_selection import GridSearchCV
#from sklearn import linear_model
#import numpy as np
#logistic = linear_model.LogisticRegression()
#penalty = ['l1', 'l2']
#C = np.logspace(6,8,10)
#hyperparameters = dict(C=C, penalty=penalty)
#clf = GridSearchCV(logistic, hyperparameters, scoring='f1', cv=5, verbose=0)
#y_fit=clf.fit(vAR_X_TRAIN,vAR_Y_TRAIN)
#y_pred = clf.predict(vAR_X_TEST)

In [ ]:
#from sklearn.metrics import confusion_matrix
#confusion_matrix(vAR_Y_TEST, y_pred)

array([[225,  25],
       [154,  17]])

In [ ]:
#from sklearn.ensemble import RandomForestClassifier
#modelrandom3 = RandomForestClassifier(n_estimators= 100, min_samples_split= 5, min_samples_leaf=4, max_features='auto', max_depth=15, bootstrap=True)
#y_fit = modelrandom3.fit(vAR_X_TRAIN,vAR_Y_TRAIN)
#y_pred = y_fit.predict(vAR_X_TEST)
#from sklearn.metrics import confusion_matrix
#confusion_matrix(vAR_Y_TEST, y_pred)

array([[176,  74],
       [131,  40]])

In [ ]:
#from sklearn.metrics import accuracy_score
#accuracy_score(vAR_Y_TEST, y_pred)

0.5130641330166271

In [ ]:
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
#from sklearn.metrics import roc_curve, precision_recall_curve, auc, make_scorer, recall_score, accuracy_score, precision_score, confusion_matrix
#from sklearn.metrics import roc_auc_score

#from tqdm import tqdm
#random = RandomForestClassifier(n_jobs=-1)
#param_grid = {
#    'min_samples_split': [3, 5, 10], 
#    'n_estimators' : [100, 300],
#    'max_depth': [3, 5, 15, 25]
#}
#
#scorers = {
#    'precision_score': make_scorer(precision_score),
#    'recall_score': make_scorer(recall_score),
#    'accuracy_score': make_scorer(accuracy_score),
#    'roc_auc_score': make_scorer(roc_auc_score)
#}
#skf = StratifiedKFold(n_splits=5)
#clf = GridSearchCV(random, param_grid, cv=skf, scoring='f1', return_train_score=True, n_jobs=-1)
#clf = clf.fit(vAR_X_TRAIN,vAR_Y_TRAIN)

#y_pred = clf.predict(vAR_X_TEST)
#from sklearn.metrics import confusion_matrix
#confusion_matrix(vAR_Y_TEST, y_pred)

array([[163,  87],
       [124,  47]])

In [ ]:
#from sklearn.metrics import accuracy_score
#accuracy_score(vAR_Y_TEST, y_pred)

0.498812351543943

In [ ]:
#Dont run this - copying files from colab to google drive
#!cp Customer.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/
#!cp Customer_Product_Price.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/
#!cp Customer_Satisfaction.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/
#!cp Customer_Service_Quality.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/
#!cp Customer_Spending_Power.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/
#!cp Customer_label.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/
#!cp customer_buying_pattern.xlsx /content/drive/MyDrive/Customer_Churn_Datasets/